INSERT INTO "GENRE" ("GENRE_ID", "NAME")
VALUES (1, 'Комедия');
INSERT INTO "GENRE" ("GENRE_ID", "NAME")
VALUES (2, 'Драма');
INSERT INTO "GENRE" ("GENRE_ID", "NAME")
VALUES (3, 'Мультфильм');
INSERT INTO "GENRE" ("GENRE_ID", "NAME")
VALUES (4, 'Триллер');
INSERT INTO "GENRE" ("GENRE_ID", "NAME")
VALUES (5, 'Документальный');
INSERT INTO "GENRE" ("GENRE_ID", "NAME")
VALUES (6, 'Боевик');

INSERT INTO "RATING" ("RATING_ID", "NAME")
VALUES (1, 'G');
INSERT INTO "RATING" ("RATING_ID", "NAME")
VALUES (2, 'PG');
INSERT INTO "RATING" ("RATING_ID", "NAME")
VALUES (3, 'PG-13');
INSERT INTO "RATING" ("RATING_ID", "NAME")
VALUES (4, 'R');
INSERT INTO "RATING" ("RATING_ID", "NAME")
VALUES (5, 'NC-17');